services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - DATABASE_URL
      - API_PORT
      - API_DEV
      - API_CORS
      - API_RL_RPS
      - API_RL_BURST
    volumes:
      - ./api:/app

  cv:
    build: 
      context: ./cv
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL
      - MEDIAMTX_HOSTNAME
      - MEDIAMTX_PORT
    depends_on:
      mediamtx:
        condition: service_started

  mediamtx:
    image: bluenviron/mediamtx
    restart: unless-stopped
    hostname: ${MEDIAMTX_HOSTNAME}
    ports:
      - ${MEDIAMTX_PORT}:${MEDIAMTX_PORT}
    environment:
      - MTX_RTSPADDRESS=${MEDIAMTX_HOSTNAME}:${MEDIAMTX_PORT}
      - MTX_PATHS_WASHBAY1_SOURCE
      - MTX_PATHS_WASHBAY2_SOURCE
      - MTX_PATHS_WASHBAY3_SOURCE
      - MTX_PATHS_WASHBAY4_SOURCE
      - MTX_PATHS_WASHBAY5_SOURCE
      - MTX_PATHS_WASHBAY6_SOURCE
